#!/bin/sh
sudo pacman -Syu
sudo pacman -S base-devel
sudo pacman -S gnome-disk-utility
# dns dig command
sudo pacman -S bind-tool
# prime-run -> for run apps with external gpu
sudo pacman -S nvidia-prime
sudo pacman -S ttf-linux-libertine ttf-inconsolata noto-fonts
sudo pacman -S noto-fonts-cjk noto-fonts-emoji noto-fonts
sudo pacman -S gvim
sudo pacman -S wget
sudo pacman -S thunar
sudo pacman -S firefox
sudo pacman -S python-pip
sudo pacman -S xorg xorg-server xorg-xinit xorg-apps
pip install python3-xlib
# sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings
sudo pacman -S tlp
sudo pacman -S cronie
# use this with convert [param] command
sudo pacman -S imagemagick
sudo pacman -S nitrogen
sudo pacman -S file-roller
sudo pacman -S thunar
sudo pacman -S tumbler
sudo pacman -S nemo
sudo pacman -S ranger
sudo pacman -S gcc
sudo pacman -S bluez bluez-utilis blueman
sudo pacman -S pipewire  pipewire-audio pipewire-alsa pipewire-x11-bell pipewire-pulse lsp-plugins
#sudo pacman -S pulseaudio pulseaudio-bluetooth
sudo pacman -S neofetch
sudo pacman -S make
sudo pacman -S grub-customizer
# pdf reader
sudo pacman -S zathura
sudo pacman -S git
sudo pacman -S github-cli
sudo pacman -S nsxiv
sudo ln -s /usr/bin/nsxiv /usr/bin/sxiv
sudo pacman -S ntfs-3g
sudo pacman -S gedit
sudo pacman -S code
sudo pacman -S vlc
sudo pacman -S chromium
sudo pacman -S qbittorrent
sudo pacman -S obs
sudo pacman -S youtube-dl
sudo pacman -S discord
sudo pacman -S htop
sudo pacman -S cmatrix
sudo pacman -S inetutils
sudo pacman -S linux-lts linux-lts-headers
sudo pacman -S libreoffice
sudo pacman -S thunderbird
# For neofetch image backend
sudo pacman -S chafa
#enable 32 lib
#sudo vim /etc/pacman.conf
#test xorg type startx
#sudo pacman -S xorg-twm xorg-xclock xterm
#Use external lock screen with dpms
sudo pacman -S xss-lock
sudo pacman -S lib32-virtualgl
sudo pacman -S bumblebee mesa xf86-video-intel nvidia nvidia-settings lib32-nvidia-utils bbswitch nvidia-utils
nvidia-modprobe
sudo gpasswd -a $USER bumblebee
sudo systemctl enable bumblebeed.service
#sudo systemctl enable lightdm
# yay AUR helper
sudo pacman -S --needed git base-devel
cd ~/Desktop
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ~
yay -S rxvt-unicode-truecolor-wide-glyphs
yay -S visual-studio-code-bin
sudo pacman -S openvpn
yay -S openvpn-update-resolv-conf-git
sudo pacman -S jdk-openjdk
sudo pacman -S gimp
yay -S git-interactive-rebase-tool-bin
# System info gui
sudo pacman -S hardinfo
sudo pacman -S playerctl
sudo pacman -S scrot
sudo pacman -S picom
sudo pacman -S cmake
yay -S nerd-fonts-mononoki
sudo pacman -S ttf-joypixels
sudo pacman -S shellcheck
sudo pacman -S zathura-pdf-mupdf
sudo pacman -S zathura-djvu
sudo pacman -S wireless_tools
sudo pacman -S screenkey
sudo pacman -S mpv
pip3 install ueberzug
sudo pacman -S ueberzug
sudo pacman -S android-tools
sudo pacman -S clipmenu
yay -S scrcpy
#yay -S unityhub
sudo pacman -S p7zip
sudo pacman -S httrack
# Music player
sudo pacman -S cmus
sudo pacman -S qrencode
sudo pacman -S cpupower
# For gui image editing
sudo pacman -S gthumb
sudo pacman -S tk
sudo pacman -S dunst
# Text to Ascii art
sudo pacman -S figlet
sudo pacman -S nmap
sudo pacman -S smbclient
yay -S gobuster
sudo pacman -S tor
sudo pacman -S net-tools
sudo pacman -S torbrowser-launcher
sudo pacman -S impacket
sudo pacman -S openbsd-netcat
# Integrated pentesting tool for web applications
sudo pacman -S zaproxy
sudo pacman -S php
sudo pacman -S phpmyadmin
sudo pacman -S pavucontrol
sudo pacman -S ffmpegthumbnailer
sudo pacman -S tmux
sudo pacman -S ccls
sudo pacman -S nodejs
sudo pacman -S npm
sudo pacman -S gdb
sudo pacman -S mediainfo
sudo pacman -S fzf
sudo pacman -S pulsemixer
# MySQL fork
sudo pacman -S mariadb
sudo pacman -S maven
echo "Don't forget to download GraalVM to home directory"
sudo pacman -S yarn
sudo pacman -S gparted
# exiftool -> To get metadata of image
# system resource monitor
sudo pacman -S btop
sudo pacman -S docker
# css preprocessor
sudo pacman -S sassc
# code minifier
sudo pacman -S minify
sudo pacman -S zsh
sudo pacman -S zsh-syntax-highlighting
sudo pacman -S zsh-autosuggestions
sudo pacman -S fzf
# Dotfiles
sudo pacman -S stow
npm install live-server -g
# Terminal IRC client
sudo pacman -S irssi
# Game manager based on wine
sudo pacman -S lutris
# Drag and drop file share
yay -S dragon-drag-and-drop
sudo pacman -S whois
sudo pacman -S speedtest-cli
sudo pacman -S mutt
yay -S insomnia-bin
sudo pacman -S calibre
yay -S mongodb-bin
sudo pacman -S qutebrowser
# Multiple socket connection while downloading
sudo pacman -S aria2
sudo pacman -S mono
sudo pacman -S remmina
sudo pacman -S freerdp
# Disk usage analyzer
sudo pacman -S ncdu
# VHDL simulator
sudo pacman -S ghdl
# View resulting waveforms
sudo pacman -S gtkwave
# Language translate in command line
sudo pacman -S translate-shell
# Markdown server
pip install grip
sudo pacman -S ttf-nerd-fonts-symbols
# For color emojis
yay -S libxft-bgra
sudo pacman -Sy gvfs gvfs-gphoto2
# Android file transfer UI and cli tools
sudo pacman -S android-file-transfer
# Logitech user interface can be useful
sudo pacman -S solaar
sudo pacman -S plantuml
# Improve mic audio quality
# sudo pacman -S easyeffects
sudo pacman -S pandoc
yay -S quich
yay -S tuxi
echo "Don't forget to change tuxi user agent!"
printf  "\033[1;32mNoteBook FanControl Installing...\033[0m"
yay -S nbfc-linux
sudo nbfc config --apply "Acer Predator G3-572"
sudo systemctl enable nbfc_service
# LaTeX
sudo pacman -S texlive-most texlive-lang
# Biblatex
sudo pacman -S biber
# Syntax highlighted preview for vim fzf
sudo pacman -S bat
sudo pacman -S ripgrep
sudo pacman -S rofi rofi-emoji rofi-calc
sudo pacman -S stress
sudo pacman -S cups
sudo usermod -aG "$(whoami)"
sudo pacman -S system-config-printer
echo "Don't forget to start cups service for printer"
sudo pacman -S tree
yay -S android-apktool
# CLI download manager
sudo pacman -S aria2
# Quickly rename files with vim
yay -S vimv
# Mirror android device screen
sudo pacman -S scrcpy
# Apply diff files for dwm
sudo pacman -S patch
# RSS reader
sudo pacman -S newsboat
# Downgrade package group
yay -S downgrade
sudo pacman -S pyenv
# Pdf split
sudo pacman -S pdftk
# Draw on screen
yay -Ss gromit-mpx
# ChatGPT cli
pip install shell-gpt
# Terminal countdown timer
sudo pacman -S termdown
# Run slock automatically after a specific period of time
sudo pacman -S xautolock
# Sync things
sudo pacman -S syncthing
# Subtitle downloader which used in mpv
yay -S subliminal
# Chromium play with mpv deamon like tool
yay -S play-with-mpv-git
# Select area from screen
sudo pacman -S slop
# Run commands when files change
sudo pacman -S entr
# Rust language toolchain
sudo pacman -S rust
sudo pacman -S rust-analyzer
# Fast network scanner
sudo pacman -S masscan
#yay -S PrismLauncher
sudo pacman -S qemu-desktop virt-manager dnsmasq
sudo usermod -aG libvirt "$(whoami)"
sudo systemctl enable libvirtd
sudo systemctl start libvirtd
#sudo virsh net-start default
sudo virsh net-autostart default
# Backlight managment
sudo pacman -S light
sudo pacman -S kubectl
sudo pacman -S minikube
sudo pacman -S k9s
sudo pacman -S skaffold
sudo pacman -S sqlx-cli
# du + rust
sudo pacman -S dust
sudo pacman -S go-swagger
# ADR documentation generator
yay -S adr-tools
# Go migration tool
yay -S goose
sudo pacman -S helm
sudo pacman -S aws-cli-v2
yay -S anki
sudo pacman -S dive
# neofetch for git
sudo pacman -S onefetch
sudo pacman -S lazygit
yay -S lazydocker
# http load generator
sudo pacman -S hey
