#!/bin/sh
# Zenity
#OPERATION=$(zenity --width=300\
#           --height=300\
#           --list\
#           --title "bootmenu"\
#            --text "Select Operation"\
#	    --column=""\
#            "shutdown"\
#            "reboot"\
#                )
#
OPERATION=$(printf "Shutdown\nReboot\nLock" | rofi -dmenu -i)

case $OPERATION in
    'Shutdown') shutdown now;;
    'Reboot') reboot;;
    *) exit;;
esac

