#!/bin/sh

# use nmcli -f SSID... for filter output
printf "Scanning available wifi networks..."
nmcli -f 'bssid,signal,bars,freq,ssid' --color yes dev wifi list --rescan yes |
fzf \
--header-lines=1 --ansi --cycle \
--bind="enter:execute(nmcli --ask dev wifi connect {1})+abort"
