#!/bin/sh
DESKTOP=$(zenity --width=300\
           --height=350\
           --list\
           --title "dymdm"\
            --text "Select desktop"\
	    --column=""\
            "dwm"\
            "gnome"\
            "cinnamon"\
                )

case $DESKTOP in
    (dwm)
	while true; do
		dwm >/dev/null 2>&1
	done
        exec dwm;;
    (gnome)
        exec gnome-session;;
    (cinnamon)
        exec cinnamon-session;;
esac
