#!/bin/sh
SOUNDS_DIR="$HOME/Sounds"
# Load samples
pactl upload-sample "$SOUNDS_DIR/funk_bell.wav" bell-window-system
# Load modules
pactl load-module module-x11-bell sample=bell-window-system display=:0.0
