#!/bin/sh

help() {
    cat <<EOF
Usage: init-mon [OPTIONS...]

Initialize second monitor

Options:
	-l 		Initialize to left side
	-r 		Initialize to right side
	-m 		Mirror current screen
EOF
}
case $1 in
	# -l) xrandr --output HDMI-1-0 --mode 1920x1080 --left-of eDP1;;
	-l) xrandr --output HDMI-1-0 --mode 1920x1080 --left-of eDP-1;;
	# -r) xrandr --output HDMI-1-0 --mode 1920x1080 --right-of eDP1;;
	-r) xrandr --output HDMI-1-0 --mode 1920x1080 --right-of eDP-1;;
	# -m) xrandr --output HDMI-1-0 --mode 1920x1080 --same-as eDP1;;
	-m) xrandr --output HDMI-1-0 --mode 1920x1080 --same-as eDP-1;;
	*) help ;;
esac


