#!/bin/sh
# currLayout="$(setxkbmap -print | awk -F"+" '/xkb_symbols/ {printf $2}')"
# case "$currLayout" in
#     *us*)# us(altgr-intl)
#         setxkbmap tr
#         newLayout='TR'
#     ;;
#     *tr*)
#         setxkbmap -layout us -variant altgr-intl
#         newLayout='US'
#     ;;
#     *)
#         setxkbmap -layout us -variant altgr-intl
#         newLayout='US'
#     ;;
# esac
# notify-send "Keyboard layout changed to $newLayout"
currLayout="$(ibus engine)"
case "$currLayout" in
    *us*)# xkb:us::eng
        ibus engine xkb:tr::tur
        newLayout='TR'
    ;;
    *tr*)# xkb:tr:alt:tur
        ibus engine xkb:us:altgr-intl:eng
        newLayout='US'
    ;;
    *)
        ibus engine xkb:us:altgr-intl:eng
        newLayout='US'
    ;;
esac
# ibus engine anthy
# ibus engine mozc-jp
notify-send "Keyboard layout changed to $newLayout"
