#!/bin/sh

dimensions=$(xdpyinfo | grep dimensions | awk '{printf $2}')
filename=$(date "+%Y-%m-%d@%H:%M:%S.mkv")
file_path="$HOME/Videos/$filename"

help() {
    cat <<EOF
usage: record-screen [OPTIONS...]

Simple screen recording script

options:
	-h		Print this text and exit
	-v 		Record video only
	-c 		Record camera only
	-a 		Record audio only
EOF
}
case "$1" in
	# video only
	-v) ffmpeg -y -f x11grab -s $dimensions  -i :0.0 $file_path ;;
	# record camera
	-c) ffmpeg -y -i /dev/video0 $file_path ;;
	# audio only
	-a) ffmpeg -y -f alsa -i default $file_path ;;
	-h|--help) help && exit ;;
	# record video with audio
	*) ffmpeg -y -f x11grab -s $dimensions  -i :0.0 -f alsa -i default $file_path
esac
