#!/bin/bash
errlogfile="$HOME/startup.log"
printf "***Startup Script***\n"
# Increase scroll key speed
xset r rate 300 50 2>>$errlogfile
# Swap capslock and escape
setxkbmap -option caps:swapescape 2>>$errlogfile
# Start slock after 5 minute inacivity
# xautolock -time 5 -locker slock & 2>>$errlogfile
xss-lock -- slock & 2>>$errlogfile
nitrogen --restore & 2>>$errlogfile
#picom --experimental-backends --config ~/.config/picom/picom.conf & 2>>$errlogfile
picom --config ~/.config/picom/picom.conf & 2>>$errlogfile

# Load bell sound
# use xset -b to disable and xset b to enable
#xset b
# pactl upload-sample /usr/share/sounds/freedesktop/stereo/bell.oga bell
# pactl load-module module-x11-bell sample=bell

# Start kdeconnect
# /usr/lib/kdeconnectd &

dwmblocks & 2>>$errlogfile
# Start clipmenu
clipmenud & 2>>$errlogfile
# Start tlp
sudo tlp start 2>>$errlogfile
# Standby HDD
sudo hdparm -y /dev/sda 2>>$errlogfile
# Start dunst notifications
dunst & 2>>$errlogfile
# Change name server
sudo conf-dns
# Initialize sound effects
init-sounds 2>>$errlogfile
# To control media that last opened when using playerctl
playerctld daemon 2>>$errlogfile
#nohup play-with-mpv & 2>>$errlogfile
