#!/bin/sh
# copy to this path
# sudo cp suspend_rtw8821ce /usr/lib/systemd/system-sleep/.
if [ "${1}" == "pre" ]; then
  modprobe -rv rtw_8821ce
elif [ "${1}" == "post" ]; then
  modprobe -v rtw_8821ce
fi
