#!/bin/sh
script_path="$HOME/.scripts/dwm-scripts/gdate"
case $BUTTON in
	1) notify-send "$(cal -m)" ;;
	3) urxvt -hold -e bash -c "cal -m -y" ;; # urxvt
	4) $TERMINAL -e bash -c "vim $script_path" ;;
esac
# 
gdate=$(date +"📅 %a %b %d %H:%M")
printf "$gdate"
