#!/bin/sh
script_path="$HOME/.scripts/dwm-scripts/gsigstr"
case $BUTTON in
	1) notify-send -t 2000 "SSID: $(gssid)" "IP: $(gip)";;
	2) notify-send -t 2000 "Scanning available wifi networks..."; $TERMINAL -e "conn-wifi" ;;
	#3) notify-send -t 2000 "Scanning available wifi networks...";  notify-send "$(nmcli -f SSID,BARS device wifi list --rescan yes)";;
	3) cinnamon-settings network;;
	4) $TERMINAL -e bash -c "vim $script_path" ;;
esac
# Calculate wireless signal strength
gwifi=$(cat /proc/net/wireless | awk 'NR==3{printf "%d", $3*10/7}')
vpn=$(sed "s/.*/ 🔐/" /sys/class/net/tun*/operstate 2>/dev/null)
wired_status=$(cat /sys/class/net/enp*/operstate 2>/dev/null) # enp2s0
if [ $gwifi -gt 80 ]; then
	str=""
elif [ $gwifi -gt 50 ]; then
	str="直"
elif [ $gwifi -gt 30 ]; then
	str="直"
elif [ $gwifi -gt 0 ]; then
	str="直"
else
	if [ $wired_status = 'up' ]; then
		str="🔗"
		printf "$str$vpn"
		return
	else
		str="睊"
	fi
fi
#printf " %2d%%$vpn" $gwifi
printf "$str %2d%%$vpn" $gwifi
