#!/bin/sh
script_path="$HOME/.scripts/dwm-scripts/gweath"
cache_path="/tmp/gweath"
check_cache() { if [ ! -f $cache_path ]; then curl wttr.in/Bursa > $cache_path; fi;}
if [ ! -z "$1" ]; then BUTTON="$1"; fi
case $BUTTON in
	1) notify-send "Weather data is getting...";  check_cache; $TERMINAL -e "less -Srf $cache_path" ;;
	"get") notify-send "Weather data is getting...";  check_cache; $TERMINAL -e "less -Srf $cache_path" ;;
	4) $TERMINAL -e "vim $script_path" ;;
esac
printf "%4s" $(curl wttr.in/Bursa?format="%c+%t" 2>/dev/null )
